### ISSUE TITLE
warning when vacuuming

### ISSUE THREAD

**Issue by marco44** [rjuju/pg_shared_plans#2]
The whole message in the log is this:
```
2021-06-05 18:13:30.840 CEST [1507287] postgres@nextcloud WARNING:  New value for pg_shared_plans.rdepend_max (50) is lower than the previous value (500). Existing entries won't be affected.
2021-06-05 18:13:30.840 CEST [1507287] postgres@nextcloud CONTEXT:  parallel worker
```

**Comment by rjuju** [comment]
Thanks for the report!  Indeed, parallel worker explicitly set all non default GUCs to ensure that they will have the same environment as the leader process.  This can be also happen with any DML query using parallelism.

I think that simply ignoring parallel workers for that message should be enough, as the goal is to warn DBA that even though the new value is accepted, it won't enforce it immediately, so it can't be use as an immediate way to release dynamic shared memory.  This is done in https://github.com/rjuju/pg_shared_plans/commit/99e054a962d7ce5bef90e3557b20492315cc4cea.

**Comment by marco44** [comment]
Problem solved

**Comment by rjuju** [comment]
Great!
