### ISSUE TITLE
A question about postgresql query plan?

### ISSUE THREAD

**Issue by NEUguomiaomiao** [rjuju/pg_shared_plans#3]
Hello, I would like to ask how the parameters in the general query plan are brought in after fetching the query plan from the query plan cache.
For example, I have cached the query plan for the following statement in the query plan cache:
```sql
PREPARE demo(int) AS SELECT * FROM stu WHERE score>=$1;
```
Now I will execute the statement EXECUTE demo(760); He will now fetch the query plan from the cache, but do you know how the fetched query plan brings the parameter 760 in?

**Comment by rjuju** [comment]
Hi,

I don't really understand your question.  Technically this extension only bypass postgres original plan cache, which does the exact same thing: cache a plan and inject it if it thinks it's beneficial.  The only difference here is that the plans are shared in shared memory and so can be used by multiple backends.

So the parameter passing doesn't change, and is done by core postgres, either with an EXECUTE statement or a BIND message in case of extended protocol.

For instance, for an EXECUTE command, this parameters are passed there:

https://github.com/postgres/postgres/blob/master/src/backend/tcop/utility.c#L754
```
		case T_ExecuteStmt:
        			ExecuteQuery(pstate,
        						 (ExecuteStmt *) parsetree, NULL,
        						 params,
        						 dest, qc);
```

and then later in `ExecuteQuery`: 

```
	/* Evaluate parameters, if any */
	if (entry->plansource->num_params > 0)
	{
		/*
		 * Need an EState to evaluate parameters; must not delete it till end
		 * of query, in case parameters are pass-by-reference.  Note that the
		 * passed-in "params" could possibly be referenced in the parameter
		 * expressions.
		 */
		estate = CreateExecutorState();
		estate->es_param_list_info = params;
		paramLI = EvaluateParams(pstate, entry, stmt->params, estate);
	}
```

**Comment by NEUguomiaomiao** [comment]
Thank you very much for your answer. I have this question because I want to know how the general query plan in the cache has been modified so that it can correspond to the query of specific parameters. For example, when executing SQL
```sql
EXECUTE demo(760)
```
The information of parameter 760 will definitely be substituted into the general query plan, so that the corresponding results can be queried. What I want to know is at which stage postgresql substitutes the information of parameter 760

**Comment by rjuju** [comment]
The parameter will be substituted at execution.  The plan itself can be generic (and will be if it's retrieved from this extenxion), meaning that it doesn't hold any value, just placeholders to be replaced at execution time.

**Comment by NEUguomiaomiao** [comment]
Thank you very much for your reply. I just found this content through debug. Parameter substitution should occur in PortalStart function. I have a question about your plug-in. Have you customized a storage structure to cache the general query plan? I feel that the amount of code in your plug-in is relatively large now. If I just want to implement a simple query plan cache function in the plug-in, which hook will I use? Do you have any suggestions for writing postgresql plug-ins?

**Comment by rjuju** [comment]
> Have you customized a storage structure to cache the general query plan?

This plugin has no storage (at least for now), everything is kept in RAM.

> Have you customized a storage structure to cache the general query plan? 

The vast majority of the code in this plugin is not for caching a plan and retrieving it, as this part is straightforward.  The majority of the code is to handle cache invalidation, which requires to stored dependencies on relation, functions... and evict the cache when DDL are executed.

> If I just want to implement a simple query plan cache function in the plug-in, which hook will I use?

I'm not sure what exactly you want to achieve.  postgres already have a built-in local query plan cache, see https://github.com/postgres/postgres/blob/master/src/backend/utils/cache/plancache.c.  It his his pros and cons, but you can't easily bypass it (see e.g. https://github.com/rjuju/pg_shared_plans/commit/0ca2809bc6c40a2f05f0bca22a228d8ba78592e9 for some hack to avoid plancache storing a generic plan).  The hooks you need to use really depends on what you want to do and how.  The only sure one is the planner hook, obviously.

>  Do you have any suggestions for writing postgresql plug-ins?

There's no simple way to do that.  You have to use postgres insfrastructure, so you need to read and understand a lot of postgres code for that, on top of understanding the part you want to modify.  You can look at other extensions that does things close to what  you want to do to focus on the specific insfrastructure you need to understand.

**Comment by NEUguomiaomiao** [comment]
Your answer is very helpful to me. Thank you very much for your help!

**Comment by rjuju** [comment]
Thanks!
